FROM intersystemsdc/irisdemo-base-jboss:version-1.10.1
LABEL maintainer="Amir Samary <amir.samary@intersystems.com>"

# Uncomment when we have a war to add
ADD ./projects/app.war /opt/jboss/wildfly/standalone/deployments/


