#!/bin/bash

echo
echo "### HOOK - Pushing twittersrv..."
docker push ${DOCKER_REPO}:twittersrv-${DOCKER_TAG}

echo
echo "### HOOK - Pushing twittersentiment..."
docker push ${DOCKER_REPO}:twittersentiment-${DOCKER_TAG}

echo
echo "### HOOK - Pushing callcenterdb..."
docker push ${DOCKER_REPO}:callcenterdb-${DOCKER_TAG}

echo
echo "### HOOK - Pushing callcenterui..."
docker push ${DOCKER_REPO}:callcenterui-${DOCKER_TAG}