
build:
	(cd /usr/projects/callcenterbusiness-eclipse-project && mvn package install)
	(cd /usr/projects/callcenterui-eclipse-project && mvn package install)
	cp /usr/projects/callcenterui-eclipse-project/target/*.war /usr/projects/app.war